server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:file:./data/hoteldb   # store DB on disk instead of in-memory
    driver-class-name: org.h2.Driver
    username: sa
    password:                                  # keep it blank
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
